### ISSUE TITLE
SCA Contributhon <> Leaderboard Project for Discuss.layer5.io

### ISSUE THREAD

**Issue by Ruth-ikegah** [layer5io/discuss-board-solutions#14]
#### Current Behavior

The [Discuss platform for Layer5](https://discuss.layer5.io/) currently has a board showing the [top viewed](https://discuss.layer5.io/top) posts for the past year. 

#### Desired Behavior

The main idea of the project is to create a leaderboard to show the most active users on the platform based on some parameters like helpful answers, posts created, and more. That means, every contribution in the forum would count: from questions to answers to votes. Leaderboards will be updated at a specific time throughout the day.

#### Implementation

- Collect forum participation data from the database to store into another database or table called “Community Leaderboard”.
- Calculate the ranking based on the data from Community Leaderboard.
- Consume an API to show the top 5 active members on a forum page.
- Develop a  web page to display a list of all members with ranking and pagination features.

#### Resources
- Platform: https://github.com/discourse/discourse
- Our leaderboard:  https://discuss.layer5.io/u
- Discourse Leaderboard Plugin: https://meta.discourse.org/t/leaderboard-plugin/106050
- Discourse Community Leaderboard: https://meta.discourse.org/u
- Discourse Docs: https://docs.discourse.org/
- Set up Discourse locally: https://meta.discourse.org/t/how-do-i-set-up-a-local-discourse-development-environment/182882

#### Mockups

- https://github.com/konradsopala/discourse-community-leaderboard

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by Ed-Neema** [comment]
Hello Ruth. The requirements are noted.

**Comment by mzoyinda** [comment]
duly noted Ruth.

**Comment by leecalcote** [comment]
@eeshaanSA @kayceeDev @UtkarshMishra12
