### ISSUE TITLE
[Docs] Readme update needed

### ISSUE THREAD

**Issue by leecalcote** [layer5io/discuss-board-solutions#2]
**Current State:**

**Desired State:**

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by iambami** [comment]
Hey @leecalcote I can take this
Can it take the hacktoberfest label?

**Comment by leecalcote** [comment]
@iambami, oh, no. I missed your message. yes, that would be great.

**Comment by iambami** [comment]
This could be added to OpenForce issues

**Comment by verma-kunal** [comment]
@RajGM @Abhijay007 would start working on this one!

**Comment by prasanta10** [comment]
Can I work on it? This issue seems to have gone unnoticed.

**Comment by iambami** [comment]
@Abhijay007 Is this issue still opened for @prasanta10 to take it on?

**Comment by Abhijay007** [comment]
> @Abhijay007 Is this issue still opened for @prasanta10 to take it on?

@iambami I am not sure about it, but ya we definitely need a readme update and need to add everything about the project, @kayceeDev can guide better here as he is quite active in SCA :)
