### ISSUE TITLE
Issue Template Updates for Figma link 

### ISSUE THREAD

**Issue by thisiskaransgit** [layer5io/discuss-board-solutions#27]
### Current Behavior
The project's current issue templates are missing an open invitation link where new contributors can join the community's Figma team and view user interface designs and other UX projects.

### Desired Situation
Each template that has a reference to Figma in its resources section should an invite link added.

### Implementation 
```
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
```

**Acceptance Tests**
All references to Figma include the "open invite" link.

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by namitarjaria** [comment]
Hey, I can work on this.

**Comment by csengineer1990** [comment]
can I work on this? could you assign it to me?

**Comment by thisiskaransgit** [comment]
@csengineer1990, sure go ahead with this one 🚀

**Comment by csengineer1990** [comment]
Thank you, sir.
I have to paste the above-mentioned link in the [discuss-board]/ .github/ISSUE_TEMPLATE/documentation.md
am I right sir?
https://github.com/layer5io/discuss-board/blob/master/.github/ISSUE_TEMPLATE/documentation.md

**Comment by abhijeetgauravm** [comment]
I want to work on it. Can u assign me? @thisiskaransgit

**Comment by csengineer1990** [comment]
I have completed the above issue. please check.
